[package]
name = "loop-csi-provisioner"
version = "0.1.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "process", "fs", "net", "signal", "sync", "time"] }
tokio-stream = { version = "0.1.19", features = ["net"] }

rustix = { version = "1.1.5", features = ["mount", "fs"] }
linux-raw-sys = { version = "0.12.1", features = ["loop_device"] }

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

tonic = "0.14.6"
tonic-prost = "0.14.6"
prost = "0.14.4"
prost-types = "0.14.4"

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }

thiserror = "2.0.21"
anyhow = "1.0.104"

chrono = { version = "0.4.45", optional = true }
tokio-util = { version = "0.7.19", optional = true }
k8s-openapi = { version = "0.28.0", features = ["latest"], optional = true }
kube = { version = "4.2.0", optional = true }

clap = { version = "4.6.7", features = ["derive", "env"] }

[build-dependencies]
tonic-prost-build = "0.14.6"

[features]
default = ["kubernetes"]

kubernetes = ["k8s-openapi", "kube", "chrono", "tokio-util"]
