apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-loop
provisioner: loop-csi-provisioner
parameters:
  fsType: ext4
  url: nfs://127.0.0.1/share
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
